spring:
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api

debug: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: ERROR
