spring:
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      basePath: /api

debug: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: ERROR
